<?php echo $this->doctype() ?>
<html>
	<head>
		<meta charset="utf-8">
	</head>
	<body>
		<table>
			<thead></thead>
			<tbody>
				<tr>
					<td>Server-Status:</td>
					<td><?php echo ($serverStatus) ? 'Online' : 'Offline' ?></td>
				</tr>
				<tr>
					<td>Spiel:</td>
					<td><?php echo $game ?></td>
				</tr>
				<tr>
					<td>Server-Version:</td>
					<td><?php echo $serverVersion ?></td>
				</tr>
				<tr>
					<td>Server-Name:</td>
					<td><?php echo $serverName ?></td>
				</tr>
				<tr>
					<td>Passwort geschützt:</td>
					<td><?php echo ($serverStatus) ? 'Ja' : 'Nein' ?></td>
				</tr>
				<tr>
					<td>Map-Name:</td>
					<td><?php echo $map ?></td>
				</tr>
				<tr>
					<td>Spieler:</td>
					<td><?php echo '(' . $playersOnline . ' / ' . $slots . ')' ?></td>
				</tr>
			</tbody>
		</table>
	</body>
</html>
